# Generated by Django 4.1.6 on 2023-02-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.IntegerField(default=0)),
                ('score_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='askit.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=20)),
                ('question_text', models.CharField(max_length=500)),
                ('question_date', models.DateTimeField(verbose_name='date published')),
                ('question_tag', models.ManyToManyField(to='askit.tag')),
                ('question_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askit.topic')),
                ('question_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askit.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('answer_date', models.DateTimeField(verbose_name='date published')),
                ('answer_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='askit.answer')),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askit.question')),
                ('answer_tag', models.ManyToManyField(to='askit.tag')),
                ('answer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askit.user')),
            ],
        ),
    ]
